// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGV-I_2rPJrilFMXrsQTWQyIIExqJNZbM',
    appId: '1:138508260346:web:6c96c170cd0c7408a04a43',
    messagingSenderId: '138508260346',
    projectId: 'travel-agency-ba4af',
    authDomain: 'travel-agency-ba4af.firebaseapp.com',
    storageBucket: 'travel-agency-ba4af.firebasestorage.app',
    measurementId: 'G-4FVWZQDW9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_A7ejrmETBTRKpSmFARhb41Zy1Gzc-o',
    appId: '1:138508260346:android:cb98ceba8d7cef45a04a43',
    messagingSenderId: '138508260346',
    projectId: 'travel-agency-ba4af',
    storageBucket: 'travel-agency-ba4af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP6tlq1caT2qXqXRuP79dtruWmxMJdQNk',
    appId: '1:138508260346:ios:713f21e61f49649da04a43',
    messagingSenderId: '138508260346',
    projectId: 'travel-agency-ba4af',
    storageBucket: 'travel-agency-ba4af.firebasestorage.app',
    iosBundleId: 'com.example.travelAgency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP6tlq1caT2qXqXRuP79dtruWmxMJdQNk',
    appId: '1:138508260346:ios:713f21e61f49649da04a43',
    messagingSenderId: '138508260346',
    projectId: 'travel-agency-ba4af',
    storageBucket: 'travel-agency-ba4af.firebasestorage.app',
    iosBundleId: 'com.example.travelAgency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGV-I_2rPJrilFMXrsQTWQyIIExqJNZbM',
    appId: '1:138508260346:web:b3332f228e1a2996a04a43',
    messagingSenderId: '138508260346',
    projectId: 'travel-agency-ba4af',
    authDomain: 'travel-agency-ba4af.firebaseapp.com',
    storageBucket: 'travel-agency-ba4af.firebasestorage.app',
    measurementId: 'G-3ESXS8S1EL',
  );
}
